name: Python Package Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install .  # Install the package itself

    - name: Run tests
      run: |
        pytest tests # Run tests using pytest (or your test tool)

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel  # Build the source distribution and wheel

    - name: Upload package
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        skip_existing: true
